<php
error_reporting(0);
 $rand = array('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f');
$color = '#'.$rand[rand(0,15)].$rand[rand(0,15)].$rand[rand(0,15)].$rand[rand(0,15)].$rand[rand(0,15)].$rand[rand(0,15)];  
?>
<!DOCTYPE html>
  <meta charset="UTF-8">
  <meta name="description" content="Free Web Tools,  Facebook Tools,  SEO Tools ">
  <meta name="keywords" content="Online Tools,  Auto Unfriends Inactive Facebook,  Auto Unfriend,  Auto Like Facebook,  Auto Bulk Keyword ,<? echo $keyword ?>">
  <meta name="author" content="John Doe">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title> <? echo $judul; ?></title>
<link rel="shortcut icon" href="/_images/icons/BHS2.2 - Modern.ico"  type="image/x-icon" />
<link rel="icon" href="/_images/icons/BHS2.2 - Modern.ico"  type="image/x-icon" />

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mina">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=VT323">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="assets/js/typed-custom.js"></script>
<link href="https://fonts.googleapis.com/css?family=Pacifico|Ubuntu|Ubuntu+Condensed" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
body,  html{
font-family:'Roboto';
 }

.lol{
  font-family: 'Pacifico', cursive;
-webkit-animation:focus-in-expand .8s cubic-bezier(.25,.46,.45,.94) both;animation:focus-in-expand .8s cubic-bezier(.25,.46,.45,.94) both}
/* ----------------------------------------------
 * Generated by Animista on 2019-4-5 16:11:9
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
}
@-webkit-keyframes focus-in-expand{0%{letter-spacing:-.5em;-webkit-filter:blur(12px);filter:blur(12px);opacity:0}100%{-webkit-filter:blur(0);filter:blur(0);opacity:1}}@keyframes focus-in-expand{0%{letter-spacing:-.5em;-webkit-filter:blur(12px);filter:blur(12px);opacity:0}100%{-webkit-filter:blur(0);filter:blur(0);opacity:1}}

.fa {
  padding: 5px;
  font-size: 20px;
  width: 30px;
  height:30px;
  text-align: center;
  text-decoration: none;
  border-radius:50%;
}
.input {
background:none;
}
/* Add a hover effect if you want */
.fa:hover {
  opacity: 0.7;
}

/* Set a specific color for each brand */

/* Facebook */
.fa-facebook {
  background: #3B5998;
  color: white;
}

/* Twitter */
.fa-twitter {
  background: #55ACEE;
  color: white;
}
.fa-youtube {
 background:red;
 color:#fff;
}
.wobble-ver-left{
animation:wobble-ver-left .8s both
}
/* ----------------------------------------------
 * Generated by Animista on 2019-6-3 13:30:0
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes wobble-ver-left{0%,100%{transform:translateY(0) rotate(0);transform-origin:50% 50%}15%{transform:translateY(-30px) rotate(-6deg)}30%{transform:translateY(15px) rotate(6deg)}45%{transform:translateY(-15px) rotate(-3.6deg)}60%{transform:translateY(9px) rotate(2.4deg)}75%{transform:translateY(-6px) rotate(-1.2deg)}}

</style>
     


</style>
</head>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand lol" href="/"><font color="<? echo $color ?>">Inside Heartz</font></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="/about.php">About</a></li>
        
        <li><a href="/req.php">Request Tools</a></li> 
      </ul>

    </div>
  </div>
</nav>
</head>